apiVersion: v1
kind: Service
metadata:
  name: actions-service
spec:
  selector:
    app: actions
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 3000 # Port on the container (Next.js app port)
  type: LoadBalancer # Expose via external LoadBalancer for public access (use ClusterIP for internal access)
